[package]
authors = ["Jan Keith Darunday <jkcdarunday@gmail.com>"]
name = "actix-web-boilerplate"
version = "0.1.0"
edition = "2018"

[dependencies]
actix = "0.9.0"
actix-web = "2.0.0"
futures = "0.3.4"
r2d2 = "0.8.8"
r2d2-diesel = "1.0.0"
serde = "1.0.106"
serde_derive = "1.0.106"
serde_json = "1.0.51"
actix-rt = "1.1.0"

[dependencies.diesel]
features = ["postgres"]
version = "1.4.4"
