[package]
authors = ["Jan Keith Darunday <jkcdarunday@gmail.com>"]
name = "actix-web-boilerplate"
version = "0.1.0"

[dependencies]
actix = "0.7"
actix-web = "0.7"
diesel = {version="1.3.2", features=["postgres"]}
r2d2 = "0.8.2"
r2d2-diesel = "1.0.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
